NA = "NA"
def parse_cabinet_201911(name_cleaned):
    # Source: https://en.wikipedia.org/wiki/First_Gotabaya_Rajapaksa_cabinet
    return {
        "Mahinda Rajapaksa": "Prime Minister, Buddha Sasana, Cultural and Religious Affairs, Finance, Economy and Policy Development, Urban Development, Water Supply and Housing Facilities, Community Empowerment and Estate Infrastructure Development",
        "Dullas Alahapperuma": "Education, Sports and Youth Affairs",
        "Mahinda Amaraweera": "Passenger Transport Management, Power and Energy, Transport Service Management",
        "S. M. Chandrasena": "Environment and Wildlife Resources, Lands and Land Development",
        "Nimal Siripala de Silva": "Justice, Human Rights and Legal Reforms",

        "Douglas Devananda": "Fisheries and Aquatic Resources",
        "Johnston Fernando": "Ports and Shipping, Roads and Highways",
        "Bandula Gunawardana": "Higher Education, Technology and Innovation, Information and Communication Technology,  Information and Mass Media",
        "Dinesh Gunawardena": "Foreign Relations,  Skills Development, Employment and Labour Relations",
        "Ramesh Pathirana": "Plantation Industries and Export Agriculture",

        "Chamal Rajapaksa": "Internal Trade, Food Security and Consumer Welfare, Mahaweli, Agriculture, Irrigation and Rural Development",
        "Prasanna Ranaweera": "Industrial Export and Investment Promotion, Tourism and Civil Aviation",
        "Janaka Bandara Thennakoon": "Public Administration, Home Affairs, Provincial Councils and Local Government",
        # "Arumugam Thondaman✝": "Community Empowerment and Estate Infrastructure Development",
        "Pavithradevi Wanniarachchi": "Healthcare and Indigenous Medical Services, Women and Child Affairs and Social Security",
        "Wimal Weerawansa": "Industries and Supply Chain Management, Small and Medium Business and Enterprise Development",

    }.get(name_cleaned, NA)


def parse_cabinet_202008(name_cleaned):
    # Source: https://en.wikipedia.org/wiki/Second_Gotabaya_Rajapaksa_cabinet
    return {
        "Mahinda Rajapaksa": "Prime Minister, Buddha Sasana, Religious and Cultural Affairs, Economic Policy and Plan Implementation, Finance, Urban Development and Housing",
        "Rohitha Abegunawardhana": "Ports and Shipping",
        "Dullas Alahapperuma": "Power",
        "Mahindananda Aluthgamage": "Agriculture",
        "Mahinda Amaraweera": "Environment",

        "S. M. Chandrasena": "Lands",
        "Nimal Siripala de Silva": "Labour",
        "Douglas Devananda": "Fisheries",
        "Johnston Fernando": "Highways",
        "Udaya Gammanpila": "Energy",
        "Bandula Gunawardana": "Trade",

        "Dinesh Gunawardena": "Foreign Relations",
        "Gamini Lokuge": "Transport",
        "Vasudeva Nanayakkara": "Water Supply",
        "Ramesh Pathirana": "Plantation",
        "G. L. Peiris": "Education",

        "Basil Rohana Rajapaksa": "Finance",
        "Chamal Rajapaksa": "Irrigation",
        "Namal Rajapaksa": "Youth and Sports",
        "Keheliya Rambukwella": "Mass Media",
        "Prasanna Ranatunga": "Tourism",

        "C. B. Rathnayake": "Wildlife and Forest Conservation",
        "M .U. M. Ali Sabry": "Justice",
        "Janaka Bandara Thennakoon": "Public Services, Provincial Councils and Local Government",
        "Pavithradevi Wanniarachchi": "Health",
        "Sarath Weerasekera": "Public Security",

        "Wimal Weerawansa": "Industries",
    }.get(name_cleaned, NA)

def parse_cabinet_202204(name_cleaned):
    # Source: https://en.wikipedia.org/wiki/Third_Gotabaya_Rajapaksa_cabinet
    return {
        "Ranil Wickremesinghe": "Prime Minister",
        "Dilum Amunugama": "Transport and Industries",
        "Douglas Devananda": "Fisheries",
        "Channa Jayasumana": "Health",
        "G. L. Peiris": "Foreign Affairs",
        "Dinesh Gunawardena": "Public Services, Provincial Councils, and Local Government",
        "Janaka Wakkumbura": "Agriculture and Irrigation",
        "Kanchana Wijesekera": "Power and Energy",
        "M. Rameshwaran": "Education and Plantation Industries",
        "M .U. M. Ali Sabry": "Finance and Justice",
        "Mohan Priyadarshana De Silva": "Water Supply",
        "Nalaka Godahewa": "Media",
        "Naseer Ahamed": "Environment",
        "Premitha Bandara Tennakoon": "Ports and Shipping",
        "Prasanna Ranatunga": "Public Security and Tourism",
        "Ramesh Pathirana": "Education and Plantation Industries",
        "Shehan Semasinghe": "Trade and Samurdhi Development",
        "Thenuka Vidanagamage": "Sports and Youth Affairs",
        "Vidura Wickramanayaka": "Labour",
        "Wimalaweera Dissanayake": "Wildlife and Forest Resources Conservation",
    }.get(
        name_cleaned,
        NA)


DUMMY = {
    "A. Aravindh Kumar": "Unknown",
    "Abdul Haleem": "Unknown",
    "Ajith Rajapakse": "Unknown",
    "Akila Ellawala": "Unknown",
    "Ali Sabri Raheem": "Unknown",
    "Angajan Ramanathan": "Unknown",
    "Anupa Pasqual": "Unknown",
    "Anura Priyadharshana Yapa": "Unknown",
    "Anuradha Jayaratne": "Unknown",
    "Arundika Fernando": "Unknown",
    "Asanka Navarathna": "Unknown",
    "Ashok Abeysinghe": "Unknown",
    "Ashoka Priyantha": "Unknown",
    "A. L. M. Athaullah": "Unknown",
    "B. Y. G. Rathnasekara": "Unknown",
    "Basil Rohana Rajapaksa": "Unknown",
    "Buddhika Pathirana": "Unknown",
    "C. B. Rathnayake": "Unknown",
    "C.V. Wigneswaran": "Unknown",
    "Chamal Rajapaksa": "Unknown",
    "Chamara Sampath Dasanayake": "Unknown",
    "Chaminda Wijesiri": "Unknown",
    "Chandima Weerakkody": "Unknown",
    "Channa Jayasumana": "Unknown",
    "Charitha Herath": "Unknown",
    "Charles Nirmalanathan": "Unknown",
    "Mayadunna Chinthaka Amal": "Unknown",
    "D. B. Herath": "Unknown",
    "D. V. Chanaka": "Unknown",
    "D. Weerasingha": "Unknown",
    "Dayasiri Jayasekara": "Unknown",
    "Dharmalingam Sithadthan": "Unknown",
    "Diana Gamage": "Unknown",
    "Dilan Perera": "Unknown",
    "Dilip Wedaarachchi": "Unknown",
    "Dilum Amunugama": "Unknown",
    "Anura Dissanayaka": "Unknown",
    "Douglas Devananda": "Unknown",
    "Dullas Alahapperuma": "Unknown",
    "Duminda Dissanayake": "Unknown",
    "Eran Wickramaratne": "Unknown",
    "Faizal Cassim": "Unknown",
    "Sarath Fonseka": "Unknown",
    "G. G. Ponnambalam": "Unknown",
    "G. L. Peiris": "Unknown",
    "Gamini Waleboda": "Unknown",
    "Udaya Gammanpila": "Unknown",
    "Gayantha Karunatilleka": "Unknown",
    "Gayashan Nawananda": "Unknown",
    "Geetha Samanmale Kumarasinghe": "Unknown",
    "Gevindu Cumaratunga": "Unknown",
    "Govindan Karunakaram": "Unknown",
    "Gunathilaka Rajapaksha": "Unknown",
    "Bandula Gunawardana": "Unknown",
    "Dinesh Gunawardena": "Unknown",
    "H. M. M. Harees": "Unknown",
    "H. Nandasena": "Unknown",
    "Harin Fernando": "Unknown",
    "Harini Amarasuriya": "Unknown",
    "Harsha de Silva": "Unknown",
    "Harshana Rajakaruna": "Unknown",
    "Hector Appuhamy": "Unknown",
    "Hesha Withanage": "Unknown",
    "Imran Maharoof": "Unknown",
    "Imthiaz Bakeer Markar": "Unknown",
    "Indika Anuruddha Herath": "Unknown",
    "Ishak Rahuman": "Unknown",
    "Isuru Dodangoda": "Unknown",
    "J. C. Alawathuwala": "Unknown",
    "Jagath Kumara Sumithraarachchi": "Unknown",
    "Jagath Pushpakumara": "Unknown",
    "Jagath Samarawickrama": "Unknown",
    "Janaka Bandara Thennakoon": "Unknown",
    "Janaka Wakkumbura": "Unknown",
    "Nalin Bandara Jayamaha": "Unknown",
    "Jayantha Ketagoda": "Unknown",
    "Jayantha Samaraweera": "Unknown",
    "Jayantha Weerasinghe": "Unknown",
    "Jayarathna Herath": "Unknown",
    "Jeevan Thondaman": "Unknown",
    "John Seneviratne": "Unknown",
    "Johnston Fernando": "Unknown",
    "K. Kader Masthan": "Unknown",
    "K. P. S. Kumarasiri": "Unknown",
    "K. Sujith Sanjaya Perera": "Unknown",
    "Kabir Hashim": "Unknown",
    "Nalin Fernando": "Unknown",
    "Kanaka Herath": "Unknown",
    "Kanchana Wijesekera": "Unknown",
    "Kapila Athukorala": "Unknown",
    "Karunadasa Kodithuwakku": "Unknown",
    "Kavinda Heshan Jayawardhana": "Unknown",
    "Keheliya Rambukwella": "Unknown",
    "Kins Nelson": "Unknown",
    "Kokila Gunawardene": "Unknown",
    "Kulasingam Dhileeban": "Unknown",
    "Kumara Welgama": "Unknown",
    "Kumarasiri Rathnayaka": "Unknown",
    "Lakshman Kiriella": "Unknown",
    "Lalith Ellawala": "Unknown",
    "Lalith Varna Kumara": "Unknown",
    "Lasantha Alagiyawanna": "Unknown",
    "Lohan Ratwatte": "Unknown",
    "Gamini Lokuge": "Unknown",
    "M. A. Sumanthiran": "Unknown",
    "M. Rameshwaran": "Unknown",
    "M. S. Thowfeek": "Unknown",
    "M .U. M. Ali Sabry": "Unknown",
    "M. W. D. Sahan Pradeep Withana": "Unknown",
    "Madhura Withanage": "Unknown",
    "Mahinda Amaraweera": "Unknown",
    "Mahinda Rajapaksa": "Unknown",
    "Mahinda Yapa Abeywardana": "Unknown",
    "Mahindananda Aluthgamage": "Unknown",
    "Maithreepala Sirisena": "Unknown",
    "Manjula Dissanayake": "Unknown",
    "Ajith Mannapperuma": "Unknown",
    "Mano Ganesan": "Unknown",
    "Manusha Nanayakkara": "Unknown",
    "Marjan Faleel": "Unknown",
    "Mayantha Dissanayake": "Unknown",
    "Mohan Priyadarshana De Silva": "Unknown",
    "Mohomad Muzammil": "Unknown",
    "Muditha Prishanthi": "Unknown",
    "Mujibur Rahuman": "Unknown",
    "M. Udayakumar": "Unknown",
    "Nalaka Bandara Kottegoda": "Unknown",
    "Nalaka Godahewa": "Unknown",
    "Namal Rajapaksa": "Unknown",
    "Vasudeva Nanayakkara": "Unknown",
    "Naseer Ahamed": "Unknown",
    "Nimal Lanza": "Unknown",
    "Nimal Piyathissa": "Unknown",
    "Nimal Siripala de Silva": "Unknown",
    "Nipuna Ranawaka": "Unknown",
    "Niroshan Perera": "Unknown",
    "Palani Thigambaram": "Unknown",
    "Pavithradevi Wanniarachchi": "Unknown",
    "Piyal Nishantha De Silva": "Unknown",
    "Piyankara Jayaratne": "Unknown",
    "Pradeep Undugoda": "Unknown",
    "Prasanna Ranaweera": "Unknown",
    "Sajith Premadasa": "Unknown",
    "Premalal Jayasekara": "Unknown",
    "Premitha Bandara Tennakoon": "Unknown",
    "Premnath C. Dolawatte": "Unknown",
    "R. M. Ranjith Madduma Bandara": "Unknown",
    "Rajavarothiam Sampanthan": "Unknown",
    "Rajika Wickramasinghe": "Unknown",
    "Rajitha Senarathne": "Unknown",
    "Ramesh Pathirana": "Unknown",
    "Prasanna Ranatunga": "Unknown",
    "Patali Champika Ranawaka": "Unknown",
    "Ranjith Bandara": "Unknown",
    "Ranjith Siyambalapitiya": "Unknown",
    "Athuraliye Rathana": "Unknown",
    "Rauff Hakeem": "Unknown",
    "Rishad Bathiudeen": "Unknown",
    "Rohana Bandara": "Unknown",
    "Rohana Dissanayaka": "Unknown",
    "Rohini Kumari Wijerathna": "Unknown",
    "Rohitha Abegunawardhana": "Unknown",
    "Roshan Ranasinghe": "Unknown",
    "S. B. Dissanayake": "Unknown",
    "S. M. Chandrasena": "Unknown",
    "S. M. M. Muszhaaraff": "Unknown",
    "S. M. Marikkar": "Unknown",
    "S. Noharathalingam": "Unknown",
    "S. Viyalanderan": "Unknown",
    "Sagara Kariyawasam": "Unknown",
    "Samanpriya Herath": "Unknown",
    "Sampath Athukorala": "Unknown",
    "Sanath Nishantha": "Unknown",
    "Sanjeeva Edirimanna": "Unknown",
    "Sarathi Dushmantha": "Unknown",
    "Seetha Arambepola": "Unknown",
    "Selvam Adaikkalanathan": "Unknown",
    "Selvarajah Kajendren": "Unknown",
    "Shan Vijayalal De Silva": "Unknown",
    "Shanakiyan Rajaputhiran Rasamanickam": "Unknown",
    "Shantha Bandara": "Unknown",
    "Shasheendra Rajapaksa": "Unknown",
    "Shehan Semasinghe": "Unknown",
    "Siripala Gamalath": "Unknown",
    "Sisira Jayakody": "Unknown",
    "Sivagnanam Shritharan": "Unknown",
    "Sivanesathurai Santhirakanthan": "Unknown",
    "Sudarshana Denipitiya": "Unknown",
    "Sudarshini Fernandopulle": "Unknown",
    "Sudath Manjula": "Unknown",
    "Suren Raghavan": "Unknown",
    "Susil Premajayantha": "Unknown",
    "Thalatha Athukorala": "Unknown",
    "Tharaka Balasuriya": "Unknown",
    "Thavaraja Kalai Arasan": "Unknown",
    "Thenuka Vidanagamage": "Unknown",
    "Thilak Rajapakshe": "Unknown",
    "Thisakutti Arachchi": "Unknown",
    "Thushara Indunil Amarasena": "Unknown",
    "Tiran Alles": "Unknown",
    "Tissa Attanayake": "Unknown",
    "Tissa Vitarana": "Unknown",
    "U. K. Sumith Udukumbura": "Unknown",
    "Udayakantha Gunathilaka": "Unknown",
    "Udayana Kirindigoda": "Unknown",
    "Uddika Premarathne": "Unknown",
    "Upul Galappaththi": "Unknown",
    "Upul Mahendra Rajapaksha": "Unknown",
    "V. Radhakrishnan": "Unknown",
    "Vadivel Suresh": "Unknown",
    "Velu Kumar": "Unknown",
    "Vidura Wickramanayaka": "Unknown",
    "Vijitha Berugoda": "Unknown",
    "Vijitha Herath": "Unknown",
    "W. H. M. Dharmasena": "Unknown",
    "Waruna Liyanage": "Unknown",
    "Wasantha Yapabandara": "Unknown",
    "Sarath Weerasekera": "Unknown",
    "Weerasumana Weerasinghe": "Unknown",
    "Wimal Weerawansa": "Unknown",
    "Ranil Wickremesinghe": "Unknown",
    "Wijeyadasa Rajapakshe": "Unknown",
    "Wimalaweera Dissanayake": "Unknown",
    "Milan Jayathilake": "Unknown",
    "Yadamini Gunawardena": "Unknown",
}
